### ISSUE TITLE
Crash DateRange

### ISSUE THREAD

**Issue by JBAIfrance** [brianvoe/gofakeit#150]
```go
package main

import (
	"time"

	"github.com/brianvoe/gofakeit/v5"
)

func main() {
	firstJan2020 := time.Date(2020, time.January, 1, 0, 0, 0, 0, time.UTC)
	firstJan2021 := time.Date(2021, time.January, 1, 0, 0, 0, 0, time.UTC)
	gofakeit.DateRange(firstJan2020, firstJan2021)
}
```
result : 

```
panic: invalid argument to Intn

goroutine 1 [running]:
math/rand.(*Rand).Intn(0x1301f540, 0xbef20001, 0x13061ed0)
        .../math/rand/rand.go:169 +0x7b
math/rand.Intn(...)
        .../math/rand/rand.go:337
github.com/brianvoe/gofakeit/v5.randIntRange(0xb98a0000, 0x787c0000, 0x2281f581)
        .../.../vendor/github.com/brianvoe/gofakeit/v5/helpers.go:141 +0xd4
github.com/brianvoe/gofakeit/v5.Number(...)
        .../.../vendor/github.com/brianvoe/gofakeit/v5/number.go:11
github.com/brianvoe/gofakeit/v5.DateRange(0x0, 0x0, 0xd59dd800, 0xe, 0x0, 0x0, 0x0, 0xd7805d00, 0xe, 0x0, ...)
        .../.../vendor/github.com/brianvoe/gofakeit/v5/time.go:16 +0xde
main.main()
        .../.../main.go:12 +0xe0
exit status 2
```

The problem : 

```go
func DateRange(start, end time.Time) time.Time {
	return time.Unix(0, int64(Number(int(start.UnixNano()), int(end.UnixNano())))).UTC()
}
```

You cast an int64 into int (may make a negative number)

**Comment by brianvoe** [comment]
I tested this on the newest version of gofakeit and it works. I suggest upgrading to v6 and letting me know if you still have issues.

**Comment by JBAIfrance** [comment]
Have you made a test in 32 and 64 bits ? or only 64 ?

**Comment by brianvoe** [comment]
Just 64 bit. If you have a fix for it could you submit a pr please?
