### ISSUE TITLE
Cannot fill structs with faker methods that return pointers

### ISSUE THREAD

**Issue by karololszacki** [brianvoe/gofakeit#157]
Like in title, issue is with all methods that return pointers, eg. a struct with
```go
CarInfo    *gofakeit.CarInfo `fake:"{car}"`
```
will panic:

```go
package main

import (
	"fmt"
	"github.com/brianvoe/gofakeit/v6"
)


type Info struct {
	PersonInfo    *gofakeit.PersonInfo `fake:"{person}"`
}

func main() {
	var info Info
	gofakeit.Struct(&info)
	
	fmt.Print(info)
}
```

```
panic: reflect.Set: value of type *gofakeit.PersonInfo is not assignable to type gofakeit.PersonInfo

goroutine 1 [running]:
reflect.Value.assignTo(0x564ba0, 0xc00000e090, 0x196, 0x5af396, 0xb, 0x58ce60, 0x0, 0x564ba0, 0xc00008a850, 0x16)
	/usr/local/go-faketime/src/reflect/value.go:2451 +0x3f7
reflect.Value.Set(0x58ce60, 0xc00008a700, 0x199, 0x564ba0, 0xc00000e090, 0x196)
	/usr/local/go-faketime/src/reflect/value.go:1564 +0xbd
github.com/brianvoe/gofakeit/v6.rStruct(0xc000012810, 0x603bc0, 0x58ce60, 0x58ce60, 0xc00008a700, 0x199, 0x5620f1, 0x8)
	/tmp/gopath550958925/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.1/struct.go:104 +0x7fd
github.com/brianvoe/gofakeit/v6.r(0xc000012810, 0x603bc0, 0x58ce60, 0x58ce60, 0xc00008a700, 0x199, 0x5620f1, 0x8, 0xffffffffffffffff)
	/tmp/gopath550958925/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.1/struct.go:34 +0x387
github.com/brianvoe/gofakeit/v6.rStruct(0xc000012810, 0x603bc0, 0x578040, 0x578040, 0xc00008a700, 0x199, 0x0, 0x0)
	/tmp/gopath550958925/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.1/struct.go:144 +0x2e6
github.com/brianvoe/gofakeit/v6.r(0xc000012810, 0x603bc0, 0x578040, 0x578040, 0xc00008a700, 0x199, 0x0, 0x0, 0x0)
	/tmp/gopath550958925/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.1/struct.go:34 +0x387
github.com/brianvoe/gofakeit/v6.rPointer(0xc000012810, 0x603bc0, 0x565720, 0x565720, 0xc00008a700, 0x16, 0x0, 0x0, 0x0)
	/tmp/gopath550958925/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.1/struct.go:156 +0xf1
github.com/brianvoe/gofakeit/v6.r(0xc000012810, 0x603bc0, 0x565720, 0x565720, 0xc00008a700, 0x16, 0x0, 0x0, 0x0)
	/tmp/gopath550958925/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.1/struct.go:32 +0x305
github.com/brianvoe/gofakeit/v6.structFunc(0xc000012810, 0x565720, 0xc00008a700)
	/tmp/gopath550958925/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.1/struct.go:26 +0xed
github.com/brianvoe/gofakeit/v6.Struct(...)
	/tmp/gopath550958925/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.1/struct.go:16
main.main()
	/tmp/sandbox233790502/prog.go:16 +0x6e
```

---

Of course I could use it like this instead of using the `Struct`:
```go
info.PersonInfo = gofakeit.Person()
```

But I wanted a more complicated use case, with a slice/array of PersonInfo:
```go
package main

import (
	"fmt"
	
	"github.com/brianvoe/gofakeit/v6"
)


type Info struct {
	PersonInfo    *gofakeit.PersonInfo `fake:"{person}"`
	UUID          string               `fake:"{uuid}"`
}

type Bulk struct {
	Data           []Info `fakesize:"10"`
	PageNumber     int
}


func main() {
	var b Bulk
	gofakeit.Struct(&b)
	fmt.Println(&b)
}
```

I think that is a legitimate use case and I would love to get this to work...

Playground: https://play.golang.org/p/LB0tdfupHpP

**Comment by karololszacki** [comment]
A quick workaround:
```go
gofakeit.AddFuncLookup("personworkaround", gofakeit.Info{
	Category:    "custom",
	Description: "Person() but fixed pointer",
	Example:     "notworthit",
	Output:      "*gofakeit.PersonInfo",
	Generate: func(r *rand.Rand, m *gofakeit.MapParams, info *gofakeit.Info) (interface{}, error) {
		return *gofakeit.Person(), nil
    },
})
```

Playground: https://play.golang.org/p/z1VjU2i0dHQ

**Comment by brianvoe** [comment]
Ill see if i can look into this. Cause i do agree this should work without the need for a new lookup for a function that already exists

**Comment by brianvoe** [comment]
I fixed this. v6.5.0
