### ISSUE TITLE
index out of range [-1]

### ISSUE THREAD

**Issue by jim3ma** [brianvoe/gofakeit#171]
When call `http://gofakeitserver:8080/lettern?count=xxx` concurrent and continuous, it panics, and always returns `AAAAAA....` for desired length

```
2021/08/12 14:21:59 http: panic serving 11.158.55.226:43896: runtime error: index out of range [-1]
goroutine 22483 [running]:
net/http.(*conn).serve.func1(0xc000144aa0)
	/usr/local/go/src/net/http/server.go:1804 +0x153
panic(0x7338c0, 0xc000282030)
	/usr/local/go/src/runtime/panic.go:971 +0x499
math/rand.(*rngSource).Uint64(...)
	/usr/local/go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc000148a00, 0x0)
	/usr/local/go/src/math/rand/rng.go:234 +0x98
math/rand.(*Rand).Int63(...)
	/usr/local/go/src/math/rand/rand.go:85
math/rand.(*Rand).Int31(...)
	/usr/local/go/src/math/rand/rand.go:99
math/rand.(*Rand).Int31n(0xc00011b2f0, 0xc000000034, 0xc000000000)
	/usr/local/go/src/math/rand/rand.go:134 +0x5f
math/rand.(*Rand).Intn(0xc00011b2f0, 0x34, 0x0)
	/usr/local/go/src/math/rand/rand.go:172 +0x45
github.com/brianvoe/gofakeit/v6.randLetter(...)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/helpers.go:129
github.com/brianvoe/gofakeit/v6.letterN(0xc00011b2f0, 0x1d4400, 0x7573f3, 0x5)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/string.go:26 +0xa5
github.com/brianvoe/gofakeit/v6.addStringLookup.func2(0xc00011b2f0, 0xc00054a038, 0xc000356180, 0x8, 0xc0002644c0, 0x0, 0x7e5760)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/string.go:141 +0x94
main.lookupGet(0x7e92b0, 0xc000408000, 0xc00031a100)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/cmd/gofakeitserver/main.go:86 +0x3bf
main.lookup(0x7e92b0, 0xc000408000, 0xc00031a100)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/cmd/gofakeitserver/main.go:57 +0x96
net/http.HandlerFunc.ServeHTTP(0x79b9f0, 0x7e92b0, 0xc000408000, 0xc00031a100)
	/usr/local/go/src/net/http/server.go:2049 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00015e300, 0x7e92b0, 0xc000408000, 0xc00031a100)
	/usr/local/go/src/net/http/server.go:2428 +0x1ad
net/http.serverHandler.ServeHTTP(0xc00023e9a0, 0x7e92b0, 0xc000408000, 0xc00031a100)
	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc000144aa0, 0x7e9960, 0xc00026c000)
	/usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2993 +0x39b
2021/08/12 14:22:09 http: panic serving 11.124.66.154:41866: runtime error: index out of range [-1]
goroutine 23196 [running]:
net/http.(*conn).serve.func1(0xc000144a00)
	/usr/local/go/src/net/http/server.go:1804 +0x153
panic(0x7338c0, 0xc000018138)
	/usr/local/go/src/runtime/panic.go:971 +0x499
math/rand.(*rngSource).Uint64(...)
	/usr/local/go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc000148a00, 0x0)
	/usr/local/go/src/math/rand/rng.go:234 +0x98
math/rand.(*Rand).Int63(...)
	/usr/local/go/src/math/rand/rand.go:85
math/rand.(*Rand).Int31(...)
	/usr/local/go/src/math/rand/rand.go:99
math/rand.(*Rand).Int31n(0xc00011b2f0, 0xc000000034, 0xc000000000)
	/usr/local/go/src/math/rand/rand.go:134 +0x5f
math/rand.(*Rand).Intn(0xc00011b2f0, 0x34, 0x0)
	/usr/local/go/src/math/rand/rand.go:172 +0x45
github.com/brianvoe/gofakeit/v6.randLetter(...)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/helpers.go:129
github.com/brianvoe/gofakeit/v6.letterN(0xc00011b2f0, 0x1d4400, 0x7573f3, 0x5)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/string.go:26 +0xa5
github.com/brianvoe/gofakeit/v6.addStringLookup.func2(0xc00011b2f0, 0xc0001400e8, 0xc00019c280, 0x8, 0xc000218a40, 0x0, 0x7e5760)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/string.go:141 +0x94
main.lookupGet(0x7e92b0, 0xc00023eb60, 0xc000494100)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/cmd/gofakeitserver/main.go:86 +0x3bf
main.lookup(0x7e92b0, 0xc00023eb60, 0xc000494100)
	/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.7.0/cmd/gofakeitserver/main.go:57 +0x96
net/http.HandlerFunc.ServeHTTP(0x79b9f0, 0x7e92b0, 0xc00023eb60, 0xc000494100)
	/usr/local/go/src/net/http/server.go:2049 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00015e300, 0x7e92b0, 0xc00023eb60, 0xc000494100)
	/usr/local/go/src/net/http/server.go:2428 +0x1ad
net/http.serverHandler.ServeHTTP(0xc00023e9a0, 0x7e92b0, 0xc00023eb60, 0xc000494100)
	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc000144a00, 0x7e9960, 0xc00015e380)
	/usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2993 +0x39b
```

**Comment by brianvoe** [comment]
Glad to see someone using the gofakeit server. Let me see about adding the ability for the user to set a specific rand. Cause the issue is which rand type you use. I may just default set it to something that doesnt have any concurrency issues

**Comment by brianvoe** [comment]
ok i added a concurrency test and wasnt able to see the index out of range trigger. Can you do a pr and add a concurrency test that triggers an index out of range panic? Below is the test I added that didnt result in anything.

```go
func TestConcurrencyRequests(t *testing.T) {
	var wg sync.WaitGroup

	for i := 0; i < 100; i++ {
		wg.Add(1)

		go concurrencyRequestFunc(t, &wg, i)
	}
	wg.Wait()
}

func concurrencyRequestFunc(t *testing.T, wg *sync.WaitGroup, count int) {
	fmt.Println(count)
	mapData := url.Values{}
	mapData.Add("count", fmt.Sprint(100))

	var statusCode int
	testRequest(&testRequestStruct{
		Testing:     t,
		Method:      "GET",
		Path:        "/lettern",
		QueryParams: mapData,
		StatusCode:  &statusCode,
	})

	fmt.Println(statusCode)
	if statusCode != 200 {
		t.Fatalf("Was expecting 200 got %d", statusCode)
	}

	wg.Done()
}
```
