### ISSUE TITLE
throw panic 

### ISSUE THREAD

**Issue by rfyiamcool** [brianvoe/gofakeit#175]
### code 

[![4PFnER.png](https://z3.ax1x.com/2021/09/13/4PFnER.png)](https://imgtu.com/i/4PFnER)

- use `github.com/brianvoe/gofakeit/v6`
- the `faker` object is global.

### panic stdout

```go
panic: runtime error: index out of range [-1]

goroutine 73 [running]:
math/rand.(*rngSource).Uint64(...)
        /usr/local/go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc0003ee000, 0x31670b9caa5b15b2)
        /usr/local/go/src/math/rand/rng.go:234 +0x98
math/rand.(*Rand).Int63(...)
        /usr/local/go/src/math/rand/rand.go:85
math/rand.(*Rand).Int31(...)
        /usr/local/go/src/math/rand/rand.go:99
math/rand.(*Rand).Int31n(0xc0003e1ad0, 0xc0000001f4, 0xc0001565f0)
        /usr/local/go/src/math/rand/rand.go:134 +0x5f
math/rand.(*Rand).Intn(0xc0003e1ad0, 0x1f4, 0x1416c8b)
        /usr/local/go/src/math/rand/rand.go:172 +0x45
github.com/brianvoe/gofakeit/v6.getRandValue(0xc0003e1ad0, 0xc0001dfc10, 0x2, 0x2, 0x141d1db, 0x6)
        /Users/ruifengyun/go/src/git.hualala.com/ocean/logging/vendor/github.com/brianvoe/gofakeit/v6/helpers.go:67 +0x106
github.com/brianvoe/gofakeit/v6.verb(...)
        /Users/ruifengyun/go/src/git.hualala.com/ocean/logging/vendor/github.com/brianvoe/gofakeit/v6/words.go:37
github.com/brianvoe/gofakeit/v6.appName(0xc0003e1ad0, 0xc0001dfd70, 0x4)
        /Users/ruifengyun/go/src/git.hualala.com/ocean/logging/vendor/github.com/brianvoe/gofakeit/v6/app.go:27 +0x18a
github.com/brianvoe/gofakeit/v6.(*Faker).AppName(...)
        /Users/ruifengyun/go/src/git.hualala.com/ocean/logging/vendor/github.com/brianvoe/gofakeit/v6/app.go:16
main.(*BenchCrud).Insert(0xc000182360, 0x2710, 0x3b9aca00, 0xc0478524a1aa60b0, 0xffffb16b6f7c0938, 0x172ff60, 0x0, 0x0)
        /Users/ruifengyun/go/src/git.xxxx.com/ocean/logging/cmd/ab/ab.go:153 +0x366
```

**Comment by brianvoe** [comment]
If you can get me reproducible code that I can run myself I can take a look at it.

**Comment by brianvoe** [comment]
Just out of curiosity why did you close the ticket?
