### ISSUE TITLE
index out of range [-1] (gofakeit.Paragraph)

### ISSUE THREAD

**Issue by uvw** [brianvoe/gofakeit#177]
Similar to https://github.com/brianvoe/gofakeit/issues/175 and https://github.com/brianvoe/gofakeit/issues/155, intermittently seeing the following error when running `gofakeit.Paragraph()` under load:

```
panic: runtime error: index out of range [-1]

goroutine 313 [running]:
math/rand.(*rngSource).Uint64(...)
	/usr/local/opt/go/libexec/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc000908000)
	/usr/local/opt/go/libexec/src/math/rand/rng.go:234 +0x9f
math/rand.(*Rand).Int63(...)
	/usr/local/opt/go/libexec/src/math/rand/rand.go:84
math/rand.(*Rand).Int31(...)
	/usr/local/opt/go/libexec/src/math/rand/rand.go:98
math/rand.(*Rand).Int31n(0xc000194840, 0x1f4)
	/usr/local/opt/go/libexec/src/math/rand/rand.go:133 +0x59
math/rand.(*Rand).Intn(0x1729660, 0xc000194750)
	/usr/local/opt/go/libexec/src/math/rand/rand.go:171 +0x2e
github.com/brianvoe/gofakeit/v6.getRandValue(0x2, {0xc000db5d88, 0xc000904da8, 0x10f0cde})
	go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.8.0/helpers.go:67 +0xf3
github.com/brianvoe/gofakeit/v6.word(0xc000904e10)
	go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.8.0/words.go:74 +0xcf
github.com/brianvoe/gofakeit/v6.sentenceGen(0x258, 0x14, 0x186add8)
	go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.8.0/words.go:111 +0xf8
github.com/brianvoe/gofakeit/v6.sentence(0xc000904f30, 0xc001d0d5f0)
	go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.8.0/words.go:84 +0x25
github.com/brianvoe/gofakeit/v6.paragraphGen(0x0, {0x1, 0x5, 0x14, {0x1929f88, 0x1}}, 0x186add0)
	go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.8.0/words.go:139 +0x1bd
github.com/brianvoe/gofakeit/v6.paragraph(...)
	go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.8.0/words.go:98
github.com/brianvoe/gofakeit/v6.Paragraph(...)
	go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.8.0/words.go:89
```

It is not hard to reproduce the issue with large enough number of goroutines:

```go
func TestConcurrencyParagraph(t *testing.T) {
	var setupComplete sync.WaitGroup
	setupComplete.Add(1)

	var wg sync.WaitGroup
	for i := 0; i < 10000; i++ {
		wg.Add(1)
		go func() {
			setupComplete.Wait()
			gofakeit.Paragraph(1, 5, 20, " ")
			wg.Done()
		}()
	}

	setupComplete.Done()
	wg.Wait()
}
```

The version I used: `github.com/brianvoe/gofakeit/v6 v6.8.0`

**Comment by brianvoe** [comment]
The default rand.Rand source isn't safe for concurrent use. The rand package functions use a singe source protected by a mutex.

Ill update docs to better describe this issue

**Comment by brianvoe** [comment]
After a little thought on this. I have had too many people submit this issue of the index being out of range. I understand its an issue with using math rand NewSource(which is what i have to use) but its not worth it anymore even though it will take a performance hit because of it. Ill be making the update today to resolve this.

**Comment by brianvoe** [comment]
v6.9.0
