### ISSUE TITLE
6.17.0 broke structs with field of "custom" type 

### ISSUE THREAD

**Issue by tehe** [brianvoe/gofakeit#208]
**What:** Panic during runtime
**What version:** 6.17.0 and 6.18.0
**Last good version:** 6.16.0
**Go version:** 1.19

Considering this piece of code:

```
package main

import (
	"fmt"

	"github.com/brianvoe/gofakeit/v6"
)

type SomeArray []string

type SomeStruct struct {
	Field SomeArray `fake:"{countryabr}"`
}

func main() {
	s := SomeStruct{}
	gofakeit.Struct(&s)
	fmt.Println(s)
}
```

This used to work fine in **6.16.0** but does not work anymore in **6.17.0** and **6.18.0**.

In the latter two, the code above results in this panic:

```
panic: reflect.Set: value of type string is not assignable to type main.SomeArray

goroutine 1 [running]:
reflect.Value.assignTo({0x54fe80?, 0xc00009e480?, 0xc0001cd878?}, {0x58bdef, 0xb}, 0x554880, 0x0)
	/usr/local/go-faketime/src/reflect/value.go:3145 +0x2a5
reflect.Value.Set({0x554880?, 0xc0000aa0c0?, 0x0?}, {0x54fe80?, 0xc00009e480?, 0x0?})
	/usr/local/go-faketime/src/reflect/value.go:2160 +0xeb
github.com/brianvoe/gofakeit/v6.rCustom(0x10?, {0x71e820?, 0xc0000b8110?}, {0x554880?, 0xc0000aa0c0?, 0x4714d4?}, {0x5495b8?, 0xe?})
	/tmp/gopath2537032829/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.18.0/struct.go:83 +0x307
github.com/brianvoe/gofakeit/v6.rSlice(0xc0001cdb38?, {0x5eaf60, 0x554880}, {0x554880?, 0xc0000aa0c0?, 0xc0001cdb80?}, {0x5495b8, 0xc}, 0xffffffffffffffff)
	/tmp/gopath2537032829/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.18.0/struct.go:171 +0x10c
github.com/brianvoe/gofakeit/v6.r(0x5495b2?, {0x5eaf60, 0x554880}, {0x554880?, 0xc0000aa0c0?, 0x554880?}, {0x5495b8, 0xc}, 0x0?)
	/tmp/gopath2537032829/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.18.0/struct.go:47 +0x24f
github.com/brianvoe/gofakeit/v6.rStruct(0x524d9e?, {0x5eaf60, 0x55c340}, {0x55c340?, 0xc0000aa0c0?, 0x7029c0?}, {0x0, 0x0})
	/tmp/gopath2537032829/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.18.0/struct.go:134 +0x356
github.com/brianvoe/gofakeit/v6.r(0x54c240?, {0x5eaf60, 0x55c340}, {0x55c340?, 0xc0000aa0c0?, 0x7f73bc404a00?}, {0x0, 0x0}, 0x7f73e3a493a0?)
	/tmp/gopath2537032829/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.18.0/struct.go:35 +0x2c8
github.com/brianvoe/gofakeit/v6.rPointer(0x7f73bc7b0998?, {0x5eaf60?, 0x54c240?}, {0x54c240?, 0xc0000aa0c0?, 0x4435f1?}, {0x0, 0x0}, 0xc0000406a0?)
	/tmp/gopath2537032829/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.18.0/struct.go:154 +0x17a
github.com/brianvoe/gofakeit/v6.r(0x7f73bc7b05e0?, {0x5eaf60, 0x54c240}, {0x54c240?, 0xc0000aa0c0?, 0xc0000aa0c0?}, {0x0, 0x0}, 0xc0001cdf08?)
	/tmp/gopath2537032829/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.18.0/struct.go:33 +0x207
github.com/brianvoe/gofakeit/v6.structFunc(0xc000094000?, {0x54c240?, 0xc0000aa0c0?})
	/tmp/gopath2537032829/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.18.0/struct.go:27 +0xde
github.com/brianvoe/gofakeit/v6.Struct(...)
	/tmp/gopath2537032829/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.18.0/struct.go:17
main.main()
	/tmp/sandbox2580599956/prog.go:19 +0x51

Program exited.
```

I believe it's this commit: https://github.com/brianvoe/gofakeit/commit/e7010c55e5da95923828d91556c801b31de4de95

**Comment by gunturaf** [comment]
I also encountered this.

**Comment by brianvoe** [comment]
i have a "fix" for this. If i get some time today ill push an update

**Comment by gunturaf** [comment]
much obliged!

**Comment by brianvoe** [comment]
Ok sorry for the delay. I think i finally found something that works for all. Ironically happen to be pretty simple. Let me know if it tackles everyones issue. 

Thanks for pointing this out.

**Comment by tehe** [comment]
It does indeed fix my issue. Thank you!

**Comment by brianvoe** [comment]
Awesome glad to hear!
